apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: kafka-tester
  name: kafka-tester
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
        component: kafka-tester
    spec:
      containers:
      - name: kafka-tester
        image: index.caicloud.io/caicloud/kafka-tester:test